version: "3"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "subquery"
      POSTGRES_PASSWORD: "subquery"
      POSTGRES_DB: "subquery"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U subquery"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node:
    build:
      context: .
      dockerfile: ./docker/node.dockerfile
    depends_on:
      "postgres":
        condition: service_healthy
    restart: always
    environment:
      DB_USER: "subquery"
      DB_PASS: "subquery"
      DB_DATABASE: "subquery"
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=/app
      - --db-schema=app
      - --batch-size=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://subquery-node:3000/ready"]
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:v1.4.0
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
      "subquery-node":
        condition: service_started
    restart: always
    environment:
      DB_USER: "subquery"
      DB_PASS: "subquery"
      DB_DATABASE: "subquery"
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
