apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.container.name.replica}}"
  labels:
    name: "{{.Values.container.name.replica}}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: "{{.Values.serviceType}}"
  ports:
  - port: {{.Values.container.port}}
    targetPort: {{.Values.container.port}}
    protocol: TCP
    name: postgres
  selector:
    name: "{{.Values.container.name.replica}}"
