apiVersion: v1
kind: Service
metadata:
  name: subquery-api
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

spec:
  ports:
    - port: 3000
      name: web
  type: LoadBalancer
  selector:
    {{- include "subquery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
