apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: api-endpoint
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  endpoints:
  - dnsName:  {{ .Values.subquery.api.istio.dnsName }}
    recordTTL: 180
    recordType: CNAME
    targets:
    - {{ .Values.subquery.api.istio.dnsTarget }}
