apiVersion: v1
metadata:
  name: subquery-api-secrets
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

kind: Secret
type: Opaque
data:
  DB_PASS: {{ .Values.db.password | b64enc | quote }}
