apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: subquery-api-secrets
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  backendType: gcpSecretsManager
  projectId: {{ $.Values.db.gcpProject }}
  data:
    - name: "DB_PASS"
      key: {{ $.Values.db.gcpSecret }}
      property: POSTGRES_PASSWORD
