apiVersion: v1
kind: ConfigMap
metadata:
  name: subquery-api-config
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

data:
  DB_DATABASE: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_HOST: "subquery-db"
  DB_PORT: "5432"
