subquery:
  node:
    image: gcr.io/fetch-ai-sandbox/subquery-node
    tag: 239fe08
    startBlock: "827201"
    networkEndpoint: https://rpc-dorado.fetch.ai:443
    chainId: "dorado-1"
    batchSize: 1

  api:
    image: gcr.io/fetch-ai-sandbox/subquery-api
    tag: v1.4.0

    replicas: 1

    dns:
      # Gateways
      ingressGateway: "istio-fetch-gaia-ig"

      # DNS Settings
      name: staging.subquery.sandbox-london-b.fetch-ai.com
      target: "gaia.sandbox-london-b.fetch-ai.com"
      additionalDnsNames: []

  genesis_processor:
    image: gcr.io/fetch-ai-images/subquery-genesis-processor
    tag: v2
    genesisFile: https://storage.googleapis.com/fetch-ai-testnet-genesis/genesis-dorado-827201.json

db:
  image: postgres # TODO: change this to our custom image
  tag: 14-alpine

  name: subquery
  user: subquery
  schema: app
  shadowDatabase: subquery_shadow
  rootDatabase: postgres
  
  gcpProject: fetch-ai-sandbox
  gcpSecret: sandbox_subquery_postgres

  storageSize: 100Gi
  storageClass: csi-standard
  dataSource: data-subquery-db-migration-source-0 # NOTE: specify this if PVC need to be copied from existing PVC 
