version: 1
mode: main

subquery:
  node:
    image: gcr.io/fetch-ai-images/subquery-node
    tag: b617ee2
    startBlock: "827201"
    networkEndpoint: http://rpc-rpc-lb.dorado.svc.cluster.local:26657
    chainId: "dorado-1"

  api:
    image: gcr.io/fetch-ai-images/subquery-api
    tag: a6bf18c

    replicas: 1

db:
  image: postgres
  tag: 14-alpine

  name: subquery
  user: subquery
  gcpProject: fetch-ai-testnet-v3
  gcpSecret: testnet-subquery_postgres

  storageSize: 7Gi