subquery:
  node:
    image: gcr.io/fetch-ai-sandbox/subquery-node
    tag: fe4d558

    startBlock: 6926337
    

  api:
    image: onfinality/subql-query
    tag: v1.4.0

    replicas: 1

db:
  image: postgres
  tag: 14-alpine

  name: subquery
  user: subquery
  password: "mVsM2RcYnzMTUjWKT@9qKMT7mJXpDofeX.bFNnneCe"

  storageSize: 1Gi
