subquery:
  node:
    image: gcr.io/fetch-ai-sandbox/subquery-node
    tag: 239fe08

    startBlock: "7099815"

  api:
    image: onfinality/subql-query
    tag: v1.4.0

    replicas: 1

    istio:
      # Gateways
      ingressGateway: istio-fetch-gaia-ig

      # DNS Settings
      dnsName: subquery-staging.sandbox-london-b.fetch-ai.com
      dnsTarget: gaia.sandbox-london-b.fetch-ai.com
      additionalDnsNames: []

db:
  image: postgres
  tag: 14-alpine

  name: subquery
  user: subquery
  gcpProject: fetch-ai-sandbox
  gcpSecret: sandbox_subquery_postgres

  storageSize: 7Gi
