apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: subquery-api-preview-vsvc
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api

spec:
  gateways:
  - subquery-api-gateway

  hosts:
  - {{ .Values.subquery.api.dns.preview }}
  {{- range .Values.subquery.api.dns.additionalDnsNames }}
  - {{ . | quote }}
  {{- end }}

  http:
  - route:
    - destination:
        host: subquery-api.{{ .Values.namespace.preview }}.svc.local.cluster
        port:
          number: 3000
      weight: 100