apiVersion: v1
kind: Service
metadata:
  name: subquery-node
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: node

spec:
  ports:
    - port: 3000
      name: web
  clusterIP: None
  selector:
    {{- include "subquery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: node
