apiVersion: v1
kind: ConfigMap
metadata:
  name: subquery-db-config
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

data:
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_INITDB_ARGS: "-A scram-sha-256"
