apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: subquery-db-secrets
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
spec:
  backendType: gcpSecretsManager
  projectId: {{ $.Values.db.gcpProject }}
  data:
#    - name: "POSTGRES_USERNAME"
#      key: {{ $.Values.db.gcpSecret }}
#      property: POSTGRES_PASSWORD
    - name: "POSTGRES_PASSWORD"
      key: {{ $.Values.db.gcpSecret }}
      property: POSTGRES_PASSWORD
