apiVersion: v1
metadata:
  name: subquery-db-secrets
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

kind: Secret
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
