apiVersion: v1
kind: Service
metadata:
  name: subquery-db
  labels:
    {{- include "subquery.labels" . | nindent 4 }}
    app.kubernetes.io/component: db

spec:
  ports:
    - port: 5432
      name: psql
  clusterIP: None
  selector:
    {{- include "subquery.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
