name: Repo Quality

on:
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update
        run: sudo apt update
      - name: Install OS dependencies
        run: sudo apt install -y python3-dev nodejs

      - name: Install NodeJS dependencies
        run: yarn install

      - name: Lint TypeScript
        run: yarn lint

      - name: Codegen TypeScript
        run: yarn codegen

      - name: Build TypeScript
        run: yarn build

      - name: Run TypeScript unit tests
        run: yarn test

      # Authenticate to GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.DEVOPS_IMAGES_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - run: 'gcloud info'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: |
          gcloud auth configure-docker -q

      - name: Start-up local test environment
        uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "./ci-compose.yml"

      # NB: doing this after start-up gives the test env time to come up
      - name: Install Python dependencies
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9

      - name: Allow 45s for environment to configure properly
        uses: jakejarvis/wait-action@master
        with:
          time: '45s'

      - name: Run Python unit tests
        run: pipenv run python -m unittest discover -s ./tests/unit

      - name: Run end-to-end tests
        env:
          GITHUB_AUTHORIZATION_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: pipenv run python -m unittest discover -s ./tests/e2e
