name: Build postgres image

on: push

jobs:
  ledger-subquery:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Authenticate to GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.DEVOPS_IMAGES_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - run: 'gcloud info'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: |
          gcloud auth configure-docker -q

      # Docker build ; docker push
      - name: Build and push postgres
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/plv8.dockerfile
          push: true
          tags: |
            gcr.io/fetch-ai-images/subquery-postgres:863ce7d
